# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/framework-example',
                'doc_host': 'https://painswor28.github.io',
                'git_url': 'https://github.com/painswor28/framework-example',
                'lib_path': 'framework_example'},
  'syms': {'framework_example.core': {'framework_example.core.foo': ('core.html#foo', 'framework_example/core.py')}}}
